make syn next="none"        nextid="none"
make syn next="none"        nextid="jump"
make syn next="none"        nextid="jumpret"
make syn next="random"      nextid="none"
make syn next="hardcoded"   nextid="none"
make syn next="btb"         nextid="none"    pmarg="3_2"
make syn next="btb"         nextid="none"    pmarg="4_2"
make syn next="btb"         nextid="none"    pmarg="5_2"
make syn next="btb"         nextid="none"    pmarg="6_2"
make syn next="btb"         nextid="none"    pmarg="4_1"
make syn next="btb"         nextid="none"    pmarg="4_3"
make syn next="btb"         nextid="none"    pmarg="4_4"
make syn next="btb"         nextid="jump"    pmarg="4_2"
make syn next="btb"         nextid="jumpret" pmarg="4_2"